<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete Project_btn</name>
   <tag></tag>
   <elementGuidId>9b233be8-010c-4a92-91de-b91b0fe6ae75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;portfolio&quot;)/app-projectcard[1]/div[@class=&quot;col-xs-12 grid proj-container&quot;]/ul[@class=&quot;list-group ng-star-inserted&quot;]/li[@class=&quot;list-group-item thumbnail ng-star-inserted&quot;]/div[@class=&quot;col-xs-12&quot;]/img[@class=&quot;actionimages&quot;][count(. | //*[@alt = 'Delete Project' and @src = '../assets/images/new-images/icon_trash.svg']) = count(//*[@alt = 'Delete Project' and @src = '../assets/images/new-images/icon_trash.svg'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='portfolio']/app-projectcard/div/ul/li[42]/div[4]/img[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Delete Project</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>actionimages</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1rem</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../assets/images/new-images/icon_trash.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1rem</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;portfolio&quot;)/app-projectcard[1]/div[@class=&quot;col-xs-12 grid proj-container&quot;]/ul[@class=&quot;list-group ng-star-inserted&quot;]/li[@class=&quot;list-group-item thumbnail ng-star-inserted&quot;]/div[@class=&quot;col-xs-12&quot;]/img[@class=&quot;actionimages&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='portfolio']/app-projectcard/div/ul/li[42]/div[4]/img[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Delete Project'])[42]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[42]/div[4]/img[2]</value>
   </webElementXpaths>
</WebElementEntity>
