<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_concat(Ok here  s a list of our rental _613f26</name>
   <tag></tag>
   <elementGuidId>b9cd4a26-39d8-4575-9dbe-7284c03e5812</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='images'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slide-image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>images</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./assets/images/logo-hertz@2x.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;content&quot;]/app-chatbot[@class=&quot;ng-tns-c2-0&quot;]/div[@class=&quot;ng-tns-c2-0&quot;]/div[@class=&quot;bot-position ng-trigger ng-trigger-enterAnimation&quot;]/div[@class=&quot;chatbot px-3 py-4 ng-tns-c2-0 ng-star-inserted&quot;]/div[@class=&quot;chatbot__conversation&quot;]/div[@class=&quot;ng-tns-c2-0 ng-star-inserted&quot;]/div[@class=&quot;chatbot__chat bot ng-star-inserted&quot;]/div[@class=&quot;wheelOption ng-tns-c2-0 ng-star-inserted&quot;]/owl-carousel[@class=&quot;ng-tns-c2-0&quot;]/owl-carousel-child[@class=&quot;owl-theme row sliding owl-carousel owl-loaded owl-drag&quot;]/div[@class=&quot;owl-stage-outer&quot;]/div[@class=&quot;owl-stage&quot;]/div[@class=&quot;owl-item active&quot;]/div[@class=&quot;item ng-tns-c2-0 ng-star-inserted&quot;]/img[@class=&quot;slide-image&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='images'])[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[49]/div/div[2]/owl-carousel/owl-carousel-child/div/div/div/div/img</value>
   </webElementXpaths>
</WebElementEntity>
