<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Context Objects_rhs-object-image</name>
   <tag></tag>
   <elementGuidId>684c5a42-a512-4072-8209-c4c494d0800e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='sixjnmks']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>sixjnmks</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rhs-object-image</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/context/SVG/context_default.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;loggedIn&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 router-outlet&quot;]/app-recipetree[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-2 nav-container&quot;]/div[@class=&quot;row no-margin&quot;]/div[@class=&quot;col-sm-12 zero-padding&quot;]/app-collapsible[1]/div[@class=&quot;right-side-objects menu-item-selected&quot;]/div[@class=&quot;status collapse-context-objects showList&quot;]/div[@class=&quot;ul-box&quot;]/ul[@class=&quot;list-group col-md-12&quot;]/li[@class=&quot;list-group-item col-md-6 no-padding drag-handle&quot;]/img[@class=&quot;rhs-object-image&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='sixjnmks']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li/img</value>
   </webElementXpaths>
</WebElementEntity>
