<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_e_first-moment-box moment-img</name>
   <tag></tag>
   <elementGuidId>96c163ab-87ae-4061-b652-63602fdbf17a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='exp-sidebar']/div[2]/div[3]/div/div/div/div/ul/li/div/app-experience-static/div/div/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>first-moment-box moment-img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exp-sidebar&quot;)/div[@class=&quot;col-xs-10 main-container&quot;]/div[@class=&quot;row drawing-container&quot;]/div[@class=&quot;col-md-12 exp-tree-obj&quot;]/div[1]/div[@class=&quot;col-md-12&quot;]/div[1]/ul[@class=&quot;block-ul&quot;]/li[@class=&quot;block-panel hide-bg&quot;]/div[@class=&quot;block-container&quot;]/app-experience-static[1]/div[@class=&quot;row no-margin&quot;]/div[@class=&quot;col-sm-12 engmnt-container&quot;]/div[@class=&quot;moments&quot;]/div[@class=&quot;first-moment moment-node predictiveNode hide-recp&quot;]/div[1]/div[@class=&quot;first-moment-box moment-img&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='exp-sidebar']/div[2]/div[3]/div/div/div/div/ul/li/div/app-experience-static/div/div/div[2]/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-experience-static/div/div/div[2]/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
